name: stockspace_booking_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  gap: ^3.0.1
  get: ^4.6.6
  dio: ^5.5.0+1
  intl: ^0.19.0
  pinput: ^5.0.0
  countup: ^0.1.4
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  dropdown_button2: ^2.3.9
  percent_indicator: ^4.2.3
  expandable_page_view: ^1.0.17
  flutter_secure_storage: ^9.2.2
  flutter_image_slideshow: ^0.1.6
  flutter_carousel_widget: ^2.2.0
  form_builder_validators: ^11.0.0
  loading_animation_widget: ^1.2.1
  flutter_local_notifications: ^17.2.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/